### ISSUE TITLE
New Component: Skeleton loaders

### ISSUE THREAD

**Issue by hakimelek** [priceline/design-system#170]
Atomic components such as Text, Image, Button should have a related placeholder In order to build Skeleton screens during loading states. They should probably be built as separate components since they should be very light.

Example of a Skeleton Page in the Hotel Path:
![image](https://user-images.githubusercontent.com/1974993/33537226-8e66a2a0-d888-11e7-9a5d-5a3607240b29.png)

@odmln @chrisdroukas @jxnblk thoughts on this?

**Comment by hakimelek** [comment]
Opening this since it's back in discussion. 

@wesleymartin85 @dansternfeld1

**Comment by BeniCheni** [comment]
Thanks for re-opening the issue, @hakimelek. Given the current state of “Skeleton” used and DSv2 with the packages setup in the economy, I agree that the “Skeleton” component can be elevated to be a package from DS.

One thought I would like to highlight is that I tend to think “Shimmer” or “ShimmerContainer” seems more appropriate than “Skeleton”, as a namespace I’d package like pcln-shimmer-container.

Open to hear anyone’s thoughts though.

**Comment by wesleymartin85** [comment]
@BeniCheni I agree, calling it "Shimmer" makes a lot on sense. The "skeleton" can then be reserved to the compositions that represent the different components they are meant to represent and composed of the "Shimmer"

**Comment by dansternfeld1** [comment]
Interesting: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by craigpalermo** [comment]
Bumping this issue since we had planned to make the internal version of this shareable, but never got around to it. There are currently several unique implementations of this internally, so it'd be good to standardize.
