### ISSUE TITLE
Improve docs for `Radio` component

### ISSUE THREAD

**Issue by hakimelek** [priceline/design-system#178]
Add an example to use `Radio` with a native HTML `radiogroup` and picking up selected value.

**Comment by BeniCheni** [comment]
Gabby volunteered to pick up this issue. 🙏 @gbellini90

**Comment by gbellini90** [comment]
I will look into this and add an example over the weekend or early next week :)

**Comment by James300** [comment]
Looks like `radiogroup` is a deprecated HTML tag now: https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL/radiogroup

Closing this ticket but if somebody thinks there is value please reopen this.
