### ISSUE TITLE
Consider adding masked Input Field

### ISSUE THREAD

**Issue by hakimelek** [priceline/design-system#193]
It would be nice to have a flavor of the `InputField` component or the `InputField` itself to support Input masking. It will provide a better UX and help for form validation. Some story examples would include date input and credit card input.

**Comment by jxnblk** [comment]
I'm planning to add a MaskedInput for CC and date inputs once the lerna monorepo setup is in

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Consider adding masked Input Field](https://trello.com/c/bmfUpX2U/15-consider-adding-masked-input-field)
