### ISSUE TITLE
Refactor Hug component to become a compound component

### ISSUE THREAD

**Issue by hakimelek** [priceline/design-system#204]

**Comment by BeniCheni** [comment]
@hakimelek, can you provide more context to what the proposed refactoring for compound component would be? @suyashchopra19 and I are wondering, since we are interested in following up or closing this issue.

**Comment by James300** [comment]
Closing because we are refactoring this component tomorrow.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor Hug component to become a compound component](https://trello.com/c/bY5oarDE/16-refactor-hug-component-to-become-a-compound-component)
