### ISSUE TITLE
Add easing curves to theme

### ISSUE THREAD

**Issue by sqott-zz** [priceline/design-system#228]
easeInOut: `0.50, 0.00, 0.25, 1.00` [Example](http://cubic-bezier.com/#.5,0,.25,1)
Used for standard animations

easeOut: `0.00, 0.00, 0.25, 1.00` [Example](http://cubic-bezier.com/#0,0,.25,1)
Used for elements entering the screen

easeIn: `0.50, 0.00, 1.00, 1.00` [Example](http://cubic-bezier.com/#.5,0,1,1)
Used for elements exiting the screen

**Comment by James300** [comment]
Looks like this got merged 👍 Cleaning up this ticket now

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add easing curves to theme](https://trello.com/c/BpA4DGAj/23-add-easing-curves-to-theme)
