### ISSUE TITLE
Tooltip using a (to-be) deprecated prop

### ISSUE THREAD

**Issue by krevat** [priceline/design-system#270]
Tooltip is passing `align` into a styled `Box`, resulting in console warning.

**Comment by hakimelek** [comment]
I don't know if we can call this a deprecation, I don't see `align` exposed publicly as a proptype (anymore?). We can just go ahead and remove the `align` from Tooltip Proptype, and mention that `Tooltip` extends `Box`.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tooltip using deprecated prop](https://trello.com/c/SbWI0aQC/41-tooltip-using-deprecated-prop)
