### ISSUE TITLE
Add color pairings to theme

### ISSUE THREAD

**Issue by odmln** [priceline/design-system#291]
Would be good to add set color pairings to the theme so that components like Badge & Banner can use them. 

An example & reference can be found in @jxnblk's [styled-system](https://github.com/jxnblk/styled-system/blob/master/README.md#complex-styles).

```
colorStyles: {
  warning: {
    color: 'text',
    backgroundColor: 'orange'
  },
  error: {
    color: 'white',
    backgroundColor: 'red'
  },
}
```

**Comment by jxnblk** [comment]
I think it'd be helpful to have a complete list of what color combinations we'd want to support across all components, `warning` and `error` are a start, but I know we also have some dark and light versions, right?

**Comment by odmln** [comment]
@sqott and I sat down and came up with the following combinations. We prefaced every combo with `cs` (colorStyle) to differentiate these combos from the standard color naming convention. 

An example of implementation would be `<Badge colorStyle='csBlue' />` which will result in a badge with a blue background and white text.

```
colorStyles: {
  csText: {
    color: 'white',
    backgroundColor: 'text'
  },
  csGray: {
    color: 'white',
    backgroundColor: 'gray'
  },
  csLightGray: {
    color: 'text',
    backgroundColor: 'lightGray'
  },
  csBlue: {
    color: 'white',
    backgroundColor: 'blue',
  },
  csLightBlue: {
    color: 'blue',
    backgroundColor: 'lightBlue',
  },
  csGreen: {
    color: 'white',
    backgroundColor: 'green',
  },
  csLightGreen: {
    color: 'green',
    backgroundColor: 'lightGreen',
  },
  csRed: {
    color: 'white',
    backgroundColor: 'red',
  },
  csLightRed: {
    color: 'red',
    backgroundColor: 'lightRed',
  },
  csOrange: {
    color: 'text',
    backgroundColor: 'orange',
  },
  csLightOrange: {
    color: 'text',
    backgroundColor: 'lightOrange',
  },
  csPurple: {
    color: 'white',
    backgroundColor: 'purple',
  },
  csLightPurple: {
    color: 'purple',
    backgroundColor: 'lightPurple',
  },
  csWhiteText: {
    color: 'text',
    backgroundColor: 'white',
  },
  csWhiteGray: {
    color: 'gray',
    backgroundColor: 'white',
  },
  csWhiteBlue: {
    color: 'blue',
    backgroundColor: 'white',
  },
  csWhiteGreen: {
    color: 'green',
    backgroundColor: 'white',
  },
  csWhiteRed: {
    color: 'red',
    backgroundColor: 'white',
  },
  csWhitePurple: {
    color: 'purple',
    backgroundColor: 'white',
  },
}
```

**Comment by msafari** [comment]
let's keep the key (name of color styles) to this format:
`${textColor}On${Background}` like blueOnLightBlue

**Comment by msafari** [comment]
Will create followup issues once this is added to the theme.
