### ISSUE TITLE
Would be great to have a line height prop for Text

### ISSUE THREAD

**Issue by elizfunk** [priceline/design-system#322]
It would be great to have a line height prop for Text.

**Comment by jxnblk** [comment]
I think this should be coming in v2, see #316

**Comment by James300** [comment]
Looks like this has been resolved

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Would be great to have a line height prop for Text](https://trello.com/c/uTqcmR18/20-would-be-great-to-have-a-line-height-prop-for-text)
