### ISSUE TITLE
Hide component hardcodes `em` for breakpoint unit

### ISSUE THREAD

**Issue by msafari** [priceline/design-system#338]
I'm in the processing of overriding the default breakpoints in an app. I am overriding them with values in `px`. This causes an issue for the Hide component that uses em.
https://github.com/pricelinelabs/design-system/blob/master/src/Hide.js#L8

I think we should add a `breakpointUnit` to `theme` and use that in there.
That way anyone who is overriding the theme can change that breakpointUnit to whatever they selected.

**Comment by James300** [comment]
Theme now contains breakpoints

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hide component hardcodes em for breakpoint unit](https://trello.com/c/VZW6Dwvm/19-hide-component-hardcodes-em-for-breakpoint-unit)
