### ISSUE TITLE
Update Design System colors for v2

### ISSUE THREAD

**Issue by wesleymartin85** [priceline/design-system#354]
Change these colors to the new hex values below
```
lightGray = '#F4F6F8'
borderGray = '#C0CAD5'
gray = '#4F6F8F'
lightBlue = '#E8F2FF'
lightGreen = '#ECF7EC'
lightRed = '#FBEBEB'
orange = '#F68013'
lightPurple = '#F5EBFA'
```
Remove these colors
```
darkRed = '#800'
lightOrange = '#feb'
darkOrange = '#a50'
darkPurple = '#407'
```
Add these colors
```
textOrange = '#F06F20'
lightYellow = '#FEDC2A'
yellow = '#FFF3C0'
```

No changes needed for these colors
```
black = '#000'
white = '#fff'
text = '#001833'
darkGray = '#364049'
blue = '#007aff'
darkBlue = '#049'
green = '#0a0'
darkGreen = '#060'
red = '#c00' 
purple = '#70b'
```

**Comment by jxnblk** [comment]
Can we keep the `darkOrange` name instead of introducing `textOrange`? Would be nice to keep things parallel if possible.

Also we can alias the names of the ones to be removed to keep the number of breaking changes to a minimum if that's something you'd wanna do

**Comment by wesleymartin85** [comment]
@jxnblk I am fine with both of these suggestions, I know Laura wants to remove the colors eventually to simplify the color pairings to help with future theming for white labels but to get v2 out it makes sense to reduce the number of breaking changes.

**Comment by jxnblk** [comment]
We'd still get rid of the color values, just map the names to colors that are similar but staying in the code base

**Comment by wesleymartin85** [comment]
so `darkRed` just becomes `red`, `darkPurple` becomes `purple`, the `darkOrange` we said we would use instead of adding `textOrange`. So that just leaves `lightOrange`. For that I guess we can just use `orange`?

**Comment by jxnblk** [comment]
We also have these color combinations defined, and some of them use the deprecated colors – should those combinations be removed? https://github.com/pricelinelabs/design-system/blob/next/src/theme.js#L102-L179

These are only in the `next` branch and are not currently being used

**Comment by jxnblk** [comment]
Also looks like `darkRed` is used for the RedButton's hover state

**Comment by wesleymartin85** [comment]
I checked through the color combinations and all will work with the new colors. Can you add
```  
whiteOnOrange: {
color: colors.white,
backgroundColor: colors.darkOrange
}
```
As for the `RedButton`I think its okay for us to keep the `darkRed` to support it.

**Comment by jxnblk** [comment]
What do you want to do about the `textOnLightOrange` combination?

**Comment by James300** [comment]
Closing because we are moving towards the semantic naming colors now.
