### ISSUE TITLE
Can we add a display property to the Box component?

### ISSUE THREAD

**Issue by elizfunk** [priceline/design-system#376]
This would allow us to create inline-block components.

**Comment by jxnblk** [comment]
Worth discussing this at the meeting. My inclination is to suggest making an `InlineBlock` component for this purpose, similar to the `Flex` component. I think this can make reading the JSX to understand the layout a little easier.

Just curious, what sort of situations do you find inline-block useful over using flexbox layout?

**Comment by jxnblk** [comment]
I feel like we might want to combine this and #378 into a single issue to discuss the overall Box component API

**Comment by James300** [comment]
Closing for now since we can use a styled component wrapper to achieve this behaviour and have been void of discussion for a year now. However, if this is a common enough customization then we should look into this more.
