### ISSUE TITLE
Can we add a border-radius prop to Box and Image?

### ISSUE THREAD

**Issue by elizfunk** [priceline/design-system#378]

**Comment by jxnblk** [comment]
I think this brings up an interesting point about how we want the design system components to work. I think there's two general directions this sort of thing can go:

1. Have fewer components that have more props
2. Have more components with fewer props

For 1, it can mean more logic during runtime, and for 2, it can mean slightly larger bundle sizes. It can also affect the API/learning curve of the design system, and we should definitely discuss in the weekly meeting

**Comment by James300** [comment]
Closing for now since we can use a styled component wrapper to achieve this behaviour and have been void of discussion for a year now. However, if this is a common enough customization then we should look into this more.
