### ISSUE TITLE
Improve docs for the monorepo/lerna setup & answer open questions

### ISSUE THREAD

**Issue by BeniCheni** [priceline/design-system#389]
- Improve docs for the monorepo/lerna setup

- Answer

 open questions.

Ping, CC / @broox9 , we'll try out an overview of the monorepo/lerna setup in next WG session. Please  do not hesitate to ask any open questions here, before we have the next WG

**Comment by craigpalermo** [comment]
I think the docs have gone through a few iterations since this issue was opened. Closing for now, and we can create separate issues if updates to specific sections are desired.
