### ISSUE TITLE
Update styles to design-system slider 

### ISSUE THREAD

**Issue by wesleymartin85** [priceline/design-system#399]
New shadow for the toggles:

0px 2px 4px 0px rgba(0,0,0,0.24), 0px 2px 4px 0px rgba(0,0,0,0.16)

edit to Toggle   { margin-top: -14px;}

edit to slider rail { height: 4px; new background color borderGray;

edit Slider Div { padding-top: 14px;}

<img width="723" alt="screen shot 2018-10-29 at 10 11 48 am" src="https://user-images.githubusercontent.com/32308814/47655296-1677df00-db63-11e8-96b8-3cc028961a52.png">

**Comment by jxnblk** [comment]
Should these shadow values replace some of the current ones in the theme? I assume the one-off padding values will be okay to hard-code into the component

**Comment by jxnblk** [comment]
Also, could be helpful to have a screenshot or mock for reference

**Comment by craigpalermo** [comment]
@wesleymartin85 is this still relevant? I'd like to close it if not.

**Comment by wesleymartin85** [comment]
@craigpalermo you can go ahead and close this
