### ISSUE TITLE
Enable es6 build exports

### ISSUE THREAD

**Issue by hakimelek** [priceline/design-system#401]
Currently the design-system transpiles all the files separately using babel into a `dist` folder. We would like to support ES6 module builds using Rollup. This should enable treeshaking for apps using webpack. cc @bertya @jxnblk

**Comment by hakimelek** [comment]
I have started a [branch](https://github.com/pricelinelabs/design-system/tree/feat/es-build) which currently include a rollup config that adds transpiling a `dist/pcln-design-system.esm.js` file to the `dist` folder and keeping the same babel build for backward compatibility. I tested the build in storybook and will have to do more testing on consuming apps.

**Comment by dansternfeld1** [comment]
We need to extend Rollup and ESM export to all exported components to prevent publishing issues related to the components without those exports right now (icons, popover, autocomplete, etc)

**Comment by sdalonzo** [comment]
Issue is resolved by the new build process in v3.0.0
