### ISSUE TITLE
Should we add AMP Components to the design system?

### ISSUE THREAD

**Issue by James300** [priceline/design-system#409]
The SEO team has created a large library of AMP components which mimic the UI/UX of the Priceline components. Do we want these as a package in the design system?

What is AMP?
https://www.ampproject.org/

- James Stewart

**Comment by BeniCheni** [comment]
There's a "monorepo" in the [`packages/` folder`next` branch](https://github.com/pricelinelabs/design-system/tree/next/packages), which seesm to fit your idea of AMP component(s) / package(s). Though, this design system project focuses on styles & reusability of UI components. We should be careful about "putting" too much logic in these components.

**Comment by James300** [comment]
Closing since I don't think AMP is a big initiative of our's right now.
