### ISSUE TITLE
FormField icon disappears when using autofill

### ISSUE THREAD

**Issue by jes708** [priceline/design-system#410]
If you autofill an input within a FormField, its Icon will be obscured.

<img width="737" alt="screen shot 2018-11-08 at 10 29 21 am" src="https://user-images.githubusercontent.com/16601510/48208620-3cf70080-e341-11e8-9798-5e74c9f98326.png">

**Comment by jxnblk** [comment]
Related: https://github.com/facebook/react/issues/1159

**Comment by craigpalermo** [comment]
Confirmed that this is no longer an issue.
