### ISSUE TITLE
Consider adding whiteSpace prop to Text

### ISSUE THREAD

**Issue by jes708** [priceline/design-system#412]
`Text` should potentially have a whiteSpace prop, especially useful for setting nowrap.

**Comment by sdalonzo** [comment]
and `lineHeight`, in working with design i've had to wrap `Text` in `styled` to add only line-height lots of times

**Comment by jxnblk** [comment]
What is the use-case for `white-space: nowrap`? Typically you wouldn't want to use that in a responsive design with flexbox, and we already have a `Truncate` component

@sdalonzo v2 has a `lineHeight` prop on `Text` already FWIW

**Comment by jes708** [comment]
Here's an example @jxnblk .  We always want "EXPRESS DEAL" and "SAVE UP TO 40%" to appear as one line each, and determine the width of the Flex, so that we don't have to do trial and error to determine a pixel width the Flex needs to be to achieve this same effect.

<img width="282" alt="screen shot 2018-11-19 at 10 56 48 am" src="https://user-images.githubusercontent.com/16601510/48718692-e663af00-ebe9-11e8-8d00-2cd2c5e68879.png">

**Comment by jes708** [comment]
@jxnblk regarding `lineHeight`, do we want that on `Text`?  Shouldn't `line-height` be determined by the `theme`?  Alignment issues with icons can typically be resolved with Flex align.

**Comment by jxnblk** [comment]
> We always want "EXPRESS DEAL" and "SAVE UP TO 40%" to appear as one line each

I think this would normally be handled with a min-width, but that's probably an issue with the mockups – that said, I don't think this is a super common use-case, and it might make sense to use styled-components to extend the Text component in cases like this, rather than add a style prop. Adding a style prop makes it seem like a recommended way to do things, which I would argue that it's not

**Comment by jxnblk** [comment]
Standard line-heights are in the theme, but we opted to adding a prop in Text to control it as well. See https://github.com/pricelinelabs/design-system/blob/next/packages/core/src/theme.js#L41-L44

But yes, typically, alignment issues can be handled with the Flex component

**Comment by jamesg1** [comment]
Could you not have a box with two text components in it?
