### ISSUE TITLE
Error "keyframe declaration" on 1.0.4.

### ISSUE THREAD

**Issue by BryanEdison** [priceline/design-system#423]
Getting same issue as #415 when trying to use pcln-design-system, version 1.0.4, on create-react-app.
Works when downgrading to version 

1.0.2.
 
![image](https://user-images.githubusercontent.com/31049847/49748472-bb61fd80-fc73-11e8-92c9-a968699d14c9.png)

**Comment by BeniCheni** [comment]
Seems #361 would fix it, based on [similar comment](https://github.com/pricelinelabs/design-system/issues/415#issuecomment-439608948) in #415.

**Comment by pkhodaveissi** [comment]
I have the same error with styled-components 4.0.2, trying to downgrade to 3 to see things would work or not

**Comment by James300** [comment]
Closing for now as it seems like a fixed issue, feel free to re-open if I'm wrong.
