### ISSUE TITLE
Contributor Toolset

### ISSUE THREAD

**Issue by BeniCheni** [priceline/design-system#427]
Related to #426, a toolset to automate to maintain the contributors would be helpful. Analysis and implement a toolset & automation to maintain the contributor thumbnails.

**Comment by unscsprt** [comment]
Thanks for the suggestion @BeniCheni, that would be a good tool to have. I'll leave myself assigned for the time being, but it would be great if someone wants to take ownership of this.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Contributor Toolset](https://trello.com/c/aiLoGxs2/38-contributor-toolset)
