### ISSUE TITLE
Priceline icon (like the favicon)

### ISSUE THREAD

**Issue by BeniCheni** [priceline/design-system#433]
> does anyone know if we have a large Priceline icon (like the favicon)?

A question about priceline icon was inquired. Wonder if we can have a conversation to cover this topic.

cc @747823 / @wesleymartin85

**Comment by James300** [comment]
Is this something we still want and would this be a Priceline svg or the Priceline `P` as an svg?

**Comment by craigpalermo** [comment]
@wesleymartin85 is this something that will be included in the upcoming new icons?
