### ISSUE TITLE
responsive Icon size

### ISSUE THREAD

**Issue by krevat** [priceline/design-system#441]
Can we have `<Icon />` accept an array of sizes instead of just one? Maybe `fontSize`?

I noticed [this issue](https://github.com/pricelinelabs/design-system/issues/46) was opened and closed but it was just docs related. Is that because the capability was shot down / removed or because the capability didn't exist?

**Comment by bertya** [comment]
After discussion, we want to move forward with this. We want to use `size` to accept an array.

**Comment by dansternfeld1** [comment]
@adhagam -- please work with @sdalonzo and @gbellini90 to see how they did similar work on outline states

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Responsive Icon Size](https://trello.com/c/RUkMU6IT/43-responsive-icon-size)
