### ISSUE TITLE
Add engines config to package.json, update CONTRIBUTING.md

### ISSUE THREAD

**Issue by sdalonzo** [priceline/design-system#447]
`next` branch fails to install with node `6.3.1` and npm `5.10.0` - these are common here at priceline. we should update the engines config https://docs.npmjs.com/files/package.json#engines and the contributing doc to indicate what the minimum version of each is.

**Comment by BeniCheni** [comment]
There's a WG follow-up item to validate why there's a node version requirement, which came out from the WG session as myself as the assignee. So I added self to the **Assignees** section.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add engines config to package.json](https://trello.com/c/adz89kHl/39-add-engines-config-to-packagejson)
