### ISSUE TITLE
`lerna publish` does not publish packages

### ISSUE THREAD

**Issue by BeniCheni** [priceline/design-system#451]
`"publish": "lerna publish"` at root does not publish packages correctly. Need WG to analyze to discuss plan to address.

Current workaround is for maintainer to "_cd_" into each package and use `npm publish` to manually publish each package correctly.

**Comment by James300** [comment]
Closing because this works now.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [lerna publish does not publish packages](https://trello.com/c/0nJTKCG2/28-lerna-publish-does-not-publish-packages)
