### ISSUE TITLE
IE 11 Flex Column Img Container Bug

### ISSUE THREAD

**Issue by jes708** [priceline/design-system#461]
The following pattern causes a bug in IE11 wherein a bunch of extra height/space is added to the Image.  The problem is caused by the width on the Image-containing Box.
```
<Flex flexDirection='column'>
  <Box width={['100px', '200px']}>
    <Image />
  </Box>
  <Box />
</Flex>
```

Should this pattern be avoided or is there a way to safeguard this appropriately in the design-system?

My proposal is to enable responsive widths for the `Image` component so there is no need to add an Image container with responsive widths.

**Comment by James300** [comment]
Let's check that this is still an issue and try to fix it if so.

**Comment by unscsprt** [comment]
Confirmed this is still an issue in IE 11

**Comment by unscsprt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IE image responsiveness bug](https://trello.com/c/k7k9P8se/11-ie-image-responsiveness-bug)
