### ISSUE TITLE
SSH Keys

### ISSUE THREAD

**Issue by dansternfeld1** [priceline/design-system#462]
With the recent discussions about managing NPM profiles, we should also open our eyes to the possibility that PCLN-sensitive info may leak in other ways, including any SSH keys we generate for our internal repos. We should explicitly exclude from this repo anything that may be a security issue for Priceline, by doing things like adding .ssh folders to our ignore files.

**Comment by BeniCheni** [comment]
@dansternfeld1, I’ve seen that there was an effort to revoke collaborators with ssh, and we have ensured to re-invite the adequate collaborators, and suggested 2FA going forward.

There was also an audit conducted by me, to ensure no PCLN proprietary info in “package-lock.json”.

Believe that we can close this issue?

**Comment by dansternfeld1** [comment]
@BeniCheni let's wait until after InfoSec presents to the group next week -- there may be elements of this we're not thinking about.

**Comment by sdalonzo** [comment]
@BeniCheni @dansternfeld1 i think we can close this out with the incoming PR to augment .gitignore

**Comment by BeniCheni** [comment]
+1 for go ahead to close, since we were trained by Security. Closed issues can always be re-opened to re-track, if any unresolved concern.

**Comment by James300** [comment]
Closing this based on the discussion above.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SSH Keys](https://trello.com/c/gLnDKhGy/22-ssh-keys)
