### ISSUE TITLE
Add Modal to Docs Site

### ISSUE THREAD

**Issue by jes708** [priceline/design-system#471]
The Modal component should be showcased on our docs site

https://pricelinelabs.github.io/design-system/

**Comment by BeniCheni** [comment]
Nice suggestion, @jes708. Tagged with "help wanted" and "good first issue" labels.

**Comment by unscsprt** [comment]
@jes708 Thanks for raising this issue. I'm going to address it shortly.

**Comment by James300** [comment]
Issue is fixed

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Modal to Docs Site](https://trello.com/c/6sx4GMfy/27-add-modal-to-docs-site)
