### ISSUE TITLE
Add Autocomplete to Docs Site

### ISSUE THREAD

**Issue by BeniCheni** [priceline/design-system#473]
Would be great to add `Autocomplete` to [docs site](https://pricelinelabs.github.io/design-system/).

**Comment by unscsprt** [comment]
Making a note that I'll address this in the next week.

**Comment by James300** [comment]
Closing since we are moving to storybook docs

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Autocomplete to Docs Site](https://trello.com/c/72UFuJCh/45-add-autocomplete-to-docs-site)
