### ISSUE TITLE
FormField inputs break when value prop is provided

### ISSUE THREAD

**Issue by craigpalermo** [priceline/design-system#495]
# Demo
![Screen-Recording-2019-05-16-at-9 49 41-AM](https://user-images.githubusercontent.com/3260642/57859086-42d21080-77c0-11e9-969a-b007bb0994ed.gif)

# Expected behavior
Input text should be vertically centered regardless of whether or not the `value` prop is used. This bug only affects v2.

**Comment by unscsprt** [comment]
It looks like the fix in #497 no longer works, so the behavior described in the original issue still persists.

**Comment by craigpalermo** [comment]
Confirming that this issue is no longer present in `3.2.0`.
