### ISSUE TITLE
Named imports from pcln-icons undefined fail without providing path

### ISSUE THREAD

**Issue by unscsprt** [priceline/design-system#499]
Can we investigate why named imports don't work as expected? See the examples below for the current ways to import icon components.  

**Working:**
- `import { Close } from 'pcln-icons/lib'`
- `import Close from 'pcln-icons/lib/Close'`

**Not working:**
- `import { Close } from 'pcln-icons'`

**Comment by dansternfeld1** [comment]
Work with @unscsprt

**Comment by James300** [comment]
Fixing this tomorrow with Steve's updates to pcln-icons

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Named imports from pcln-icons undefined fail without providing path](https://trello.com/c/CNfpsrpM/21-named-imports-from-pcln-icons-undefined-fail-without-providing-path)
