### ISSUE TITLE
Popover import requires explicit "dist" path

### ISSUE THREAD

**Issue by BeniCheni** [priceline/design-system#504]
Popover import requires an explicit "dist" path currently w. a fix from #502. A follow up would be great to triage and patch the Popover (seems to apply to other packages as well) export pattern. The goal is that the import path can just use `pcln-popover`, without having to define any path.

```js
import Popover from 'pcln-popover/dist/index.js'
```

**Comment by James300** [comment]
This is fixed now, closing.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Popover import requires explicit dist path](https://trello.com/c/F03iUCLA/44-popover-import-requires-explicit-dist-path)
