### ISSUE TITLE
Refactor Idea: #509 PR A11y in pcln-icons

### ISSUE THREAD

**Issue by BeniCheni** [priceline/design-system#510]
Moved forward w. the productive #509, as it was stable, great feature.

This issue is to follow-up to trivial comments from the PR for follow-up discussion and relevant updates:

- [ ] https://github.com/pricelinelabs/design-system/pull/509#discussion_r289360220

- [ ] https://github.com/pricelinelabs/design-system/pull/509#discussion_r289361489

- [ ] https://github.com/pricelinelabs/design-system/pull/509#discussion_r289361666

- [ ] https://github.com/pricelinelabs/design-system/pull/509#discussion_r289362330

- [ ] https://github.com/pricelinelabs/design-system/pull/509#discussion_r289362966

- [ ] https://github.com/pricelinelabs/design-system/pull/509#discussion_r289363922

The suggested checkboxes could be followed up by a discussion in this thread, or an agreed, relevant updates in PR(s).

cc/ @adhagam for further thoughts per this issue :poi

**Comment by craigpalermo** [comment]
Closing as it seems this is no longer relevant.
