### ISSUE TITLE
Infra: travis.ymal specifies npm version for stable CI 

### ISSUE THREAD

**Issue by BeniCheni** [priceline/design-system#511]
If using npm 6.9.* locally, I could recreate the same error observed in recent failed CI instances (e.g. #507; #502). Debugged deeper and found that npm 6.4.1 is the stable version (or 6.4.* for that matter).

I think there are at least a couple of things we can do to stabilize CI:

- Denote npm version w. `< 6.9.*` in "engines" attribute of existing "package.json" of each packages within repo: autocomplete, core, icons, modal, popover & slider.

https://github.com/pricelinelabs/design-system/blob/986a12538662a61e8469dad9fef5bd301c07e020/packages/core/package.json#L70

- In `travis.yaml`:
  - update `node_js` version to `10`
  - [specific npm version](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#using-a-specific-npm-version) in `before_install` step to use 6.4.1 (or a higher version but below 6.9.* if confirmed locally)

https://github.com/pricelinelabs/design-system/blob/986a12538662a61e8469dad9fef5bd301c07e020/.travis.yml#L3

cc / @dgiraldo313 / @donnobot / @sdalonzo / @dansternfeld1 / @broox9 / @jes708 , marked "help wanted", "discussion" & "good second issue" for further Q&A and a volunteer.

**Comment by BeniCheni** [comment]
@dansternfeld1 , providing some insight of this issue that if "travis.yaml" file defines to use npm 6.9 version for CI, the npm install will fail. I could recreate locally and grab this particular `@babel/plugin-transform-runtime` error in this verbose npm debug log below.

I think the issue is to request to specify the npm version to use 6.4.1 in "travis.yaml" file, and move forward to upgrade back to use node 10 for build agent.

P.S.: I think the long-term approach can be to look into upgrading `@babel/plugin-transform-runtime` in another issue for better dep maintenance. 

```
15698 silly buildTree linking @babel/plugin-transform-runtime@7.5.5
15699 info lifecycle @babel/plugin-transform-runtime@7.5.5~preinstall: @babel/plugin-transform-runtime@7.5.5
15700 info lifecycle @babel/plugin-transform-runtime@7.5.5~install: @babel/plugin-transform-runtime@7.5.5
15701 info lifecycle @babel/plugin-transform-runtime@7.5.5~postinstall: @babel/plugin-transform-runtime@7.5.5
15702 info lifecycle undefined@undefined~install: undefined@undefined
15703 info lifecycle undefined@undefined~postinstall: undefined@undefined
15704 info buildTree Done in 2.028s
15705 info garbageCollect Done in 0s
15706 info lifecycle undefined@undefined~prepublish: undefined@undefined
15707 info runScript Done in 0s
15708 info lifecycle undefined@undefined~prepare: undefined@undefined
15709 verbose stack TypeError: Cannot read property 'length' of undefined
15709 verbose stack     at _incorrectWorkingDirectory (/Users/bchen/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:100:60)
15709 verbose stack     at /Users/bchen/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:72:44
15709 verbose stack     at /Users/bchen/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:203:12
15709 verbose stack     at /Users/bchen/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:285:20
15709 verbose stack     at FSReqWrap.oncomplete (fs.js:154:5)
15710 verbose cwd /Users/bchen/github/design-system
15711 verbose Darwin 18.7.0
15712 verbose argv "/Users/bchen/.nvm/versions/node/v10.16.0/bin/node" "/Users/bchen/.nvm/versions/node/v10.16.0/bin/npm" "ci"
15713 verbose node v10.16.0
15714 verbose npm  v6.9.0
15715 error Cannot read property 'length' of undefined
15716 verbose exit [ 1, true ]
```

**Comment by James300** [comment]
The plan is to replace Travis CI with Github Actions very soon. Closing this issue but will reopen if that attempt fails.
