### ISSUE TITLE
Add Popover to docs

### ISSUE THREAD

**Issue by hakimelek** [priceline/design-system#512]
Popover component is missing in the docs site.

**Comment by dansternfeld1** [comment]
Work with @dgiraldo313

**Comment by James300** [comment]
Closing this since we are trying to remove the docs project for v3. However, this will be added to the storybook docs.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Popover to Docs](https://trello.com/c/EvhXfu1U/42-add-popover-to-docs)
