### ISSUE TITLE
Input and Select should both use border

### ISSUE THREAD

**Issue by jes708** [priceline/design-system#529]
Only Select uses border, whereas Input uses box-shadow. This creates misalignments when both elements are used together on a form.  Input should use border as Select does currently.

**Comment by byakimchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Input and Select should both use border](https://trello.com/c/aHP1wH4r/14-input-and-select-should-both-use-border)

**Comment by byakimchuk** [comment]
Closing with the merge of https://github.com/priceline/design-system/pull/659
