### ISSUE TITLE
Icon tree-shaking messaging

### ISSUE THREAD

**Issue by sdalonzo** [priceline/design-system#543]
We haven't done a great job of communicating the value of using imports directly from `pcln-icons/lib/IconName` as far as dead-code elimination. This issue represents the work to upgrade our documentation for `core/Icon` and `pcln-icons` to include information about tree-shaking (https://webpack.js.org/guides/tree-shaking/) and to explain why using the import from `pcln-icons/lib` can help with bundle size.

**Comment by unscsprt** [comment]
@sdalonzo Do you think we should update the existing [Icon](https://pricelinelabs.github.io/design-system/Icon/) doc page to mention `pcln-icons` and tree shaking, or should we create a separate page for `pcln-icons` similar to https://github.com/pricelinelabs/design-system/pull/551#issuecomment-519978843?

**Comment by James300** [comment]
Closing because Steve is introducing a better tree-shaking method.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Icon tree-shaking messaging](https://trello.com/c/UHPqJm7V/25-icon-tree-shaking-messaging)
