### ISSUE TITLE
Make Checkbox and Radio Accessible

### ISSUE THREAD

**Issue by adhagam** [priceline/design-system#550]
Make Checkbox and Radio fields Accessible when the they are focused

**Comment by dansternfeld1** [comment]
@dgiraldo313 please work with @adhagam

**Comment by unscsprt** [comment]
Hey @dgiraldo313, I'll start working on Checkbox. We're including that in our team's current sprint.

**Comment by dgiraldo313** [comment]
@unscsprt Ok, great. Let me know if you need any help with testing and validation. Thanks!

**Comment by James300** [comment]
This issue is done.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make Checkbox and Radio Accessible](https://trello.com/c/IJoJIugm/26-make-checkbox-and-radio-accessible)
