### ISSUE TITLE
Full screen modal

### ISSUE THREAD

**Issue by jes708** [priceline/design-system#576]
The modal should support full screen mode for smaller viewport widths.  This would entail adjusting the max-width style rule of calc(100% - 32px) that is currently in place.

**Comment by dansternfeld1** [comment]
The current thinking is to add a prop to represent that "gutter" (defaulting to 16px) and allow the caller to decide

**Comment by dansternfeld1** [comment]
@jes708  -- please try overriding the style from within your implementation
The `className` attribute is attached to the right component to allow this override:
https://github.com/pricelinelabs/design-system/blob/master/packages/modal/src/Modal.js#L170
