### ISSUE TITLE
Add documentation about getPaletteColor

### ISSUE THREAD

**Issue by jes708** [priceline/design-system#593]
`getPaletteColor` is a DS Core export but I haven't seen any documentation about it; let's add some!

**Comment by achoboter** [comment]
I'll add some documention about this and a few of the other helper utilities I added.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add getPaletteColor to docs](https://trello.com/c/6Iby85O1/49-add-getpalettecolor-to-docs)
