### ISSUE TITLE
Allow banner to accept node for the header prop

### ISSUE THREAD

**Issue by dgiraldo313** [priceline/design-system#600]
For A11y reasons, there are instances where we want the banner to accept a specific level headings in order to meet the desired outline of the page. It would be great if we could either pass in text or a node for the header section.

This ticket is a follow up to: #549

**Comment by unscsprt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Banner should accept node as prop](https://trello.com/c/0tUMLdYn/8-banner-should-accept-node-as-prop)

**Comment by James300** [comment]
Fixed now, coming in v3.
