### ISSUE TITLE
Specify React version requirement in root package

### ISSUE THREAD

**Issue by unscsprt** [priceline/design-system#605]
Design System and its sub-packages don't currently specify a minimum required version of React. Following some of the recent changes for a11y improvements that use forward refs, `react@^16.3` and `react-dom@^16.3` became implicit requirements.

To reduce confusion, we should:

- Add `react` and `react-dom` as peer dependencies to `core` and other packages
- Rename [unsafe lifecycle methods](https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles) (or refactor to eliminate them)

**Comment by theashraf** [comment]
Can i take this one ?

**Comment by sdalonzo** [comment]
resolved in #614

**Comment by James300** [comment]
Closing this ticket as the floor is defined now
