### ISSUE TITLE
Add Label and Helper Text to Input and other components

### ISSUE THREAD

**Issue by James300** [priceline/design-system#606]
Instead of wrapping the component with a Label we should be able to pass a label prop that does it for us. I would expect similar behaviour for helper text too. This should help reduce the verboseness of our current implementation.

![image](https://user-images.githubusercontent.com/9325039/66676508-a9efd600-ec35-11e9-89d4-b018bcc4a4c5.png)

**Comment by unixchad** [comment]
First phase we could just add the `helperText` prop to get the ball rolling.

@James300 Are you thinking something like this?

```
function Input(props) {
  const { helperText, ...rest } = props;

  return (
    <Fragment>
      <input {...rest} />
      {helperText && <div>{helperText}</div>}
    </Fragment>
  );
}
```
