### ISSUE TITLE
Enable Popover to trap focus in popup when open

### ISSUE THREAD

**Issue by unscsprt** [priceline/design-system#628]
I received feedback that screen reader users may be confused if they tab out of the popover's tooltip and their focus is lost or returned to an unexpected part of the page.

To solve for this, I wrapped my `renderContent` in `<FocusLock />`, which is provided by [react-focus-lock](https://www.npmjs.com/package/react-focus-lock). This prevents the user from tabbing out of the dialog without using an input (e.g. a close button) to dismiss it.

Can we add a prop to `Popover` that optionally wraps the children of `renderContent` in `<FocusLock>`?

**Comment by James300** [comment]
Fixed now so closing the issue, will be released with v3.
