### ISSUE TITLE
New Iconography

### ISSUE THREAD

**Issue by robynZhao** [priceline/design-system#635]
We need a new iconography in design-system, thanks.  
![Screen Shot 2019-10-28 at 5 05 07 PM](https://user-images.githubusercontent.com/42556833/67718044-57d4e180-f9a5-11e9-8c72-b9590dfae9ae.png)

**Comment by dansternfeld1** [comment]
Needs a name -- external-link?

**Comment by wesleymartin85** [comment]
@robynZhao @dansternfeld1  we can use this icon. 
https://material.io/resources/icons/?icon=launch&style=baseline

All of our icons in the Priceline design system are from material.io and we can add any one of them to our DS any time we find a need for one we are not yet using.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Icon: External Link](https://trello.com/c/ladiIniZ/33-new-icon-external-link)
