### ISSUE TITLE
Button Variation: Chip

### ISSUE THREAD

**Issue by James300** [priceline/design-system#646]
![image](https://user-images.githubusercontent.com/9325039/68891106-da6bd980-06e5-11ea-9500-5609a69e443c.png)

**Comment by James300** [comment]
Also this:
![image](https://user-images.githubusercontent.com/9325039/68891259-199a2a80-06e6-11ea-8eba-94a84978bce8.png)

**Comment by craigpalermo** [comment]
**Discussion notes**
An a11y-friendly version of this exists internally, so it will replace the WIP that @craigpalermo had started. Whoever works this should also coordinate with Flights so we're not duplicating effort.
