### ISSUE TITLE
Move CI over to Github Actions

### ISSUE THREAD

**Issue by James300** [priceline/design-system#657]
We want to use Github Actions instead of Travis CI.

https://github.com/features/actions

**Comment by theashraf** [comment]
Can I work on this?

**Comment by James300** [comment]
Hey @theashraf we're going to look into this next week, I'll reach out to you then if you're still interested.

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move CI to Github Actions](https://trello.com/c/nkDrqzaB/47-move-ci-to-github-actions)

**Comment by craigpalermo** [comment]
Bumping this since @sdalonzo and I are considering moving at least the build/test job from Travis to GH Actions to resolve inaccurate merge checks that are becoming a more frequent problem. This happened most recently in #854.
