### ISSUE TITLE
<Image> component does not take `width` like others

### ISSUE THREAD

**Issue by bertya** [priceline/design-system#674]
Image component does not do styled-system interpolation on the width prop, instead, it's treated as a pure HTML attribute, which is not consistent to other behaviors.

**Comment by vtjoseph** [comment]
Hi @bertya tya @wesleymartin85, is this still a valid issue? Thanks

**Comment by sdalonzo** [comment]
@vtjoseph @bertya @wesleymartin85 @unscsprt It seems like @unscsprt fixed this in a PR into the v3 branch, which has been merged. https://github.com/priceline/design-system/pull/653. Resolving this issue.
