### ISSUE TITLE
Box doesn't use layout from styled-system

### ISSUE THREAD

**Issue by danecando** [priceline/design-system#686]
I'm new to design-system & styled-system but it seems to me like the Box component should have the styled-system layout api. 

https://styled-system.com/table#layout

I'd like to be able to set a max width or responsive displays to a box item. I can of course just make a different component to include the layout api for now but I just want to see if this is intentional and not an oversight.

Thanks

**Comment by sdalonzo** [comment]
@danecando We will discuss this and get back to you. Thanks for the issue!

**Comment by craigpalermo** [comment]
Resolved in #882
