### ISSUE TITLE
Update npm run storybook script

### ISSUE THREAD

**Issue by abautist** [priceline/design-system#693]
With docs and static storybook now integrated in the CI process, the `npm run storybook` script no longer builds a static storybook. 

We should either a) remove the script all together or b) refactor the code to allow devs to build static stories if they run `npm run storybook`.

**Comment by craigpalermo** [comment]
@sdalonzo do you know if this is still relevant? It seems like it could be solved as part of https://github.com/priceline/design-system/issues/657.
