### ISSUE TITLE
Consider lifting React peerDep floor to support hooks

### ISSUE THREAD

**Issue by sdalonzo** [priceline/design-system#711]
Some teams have expressed interest in using hooks, or in elevating common components that use hooks to Design System. Given that the last holdout of internal teams is doing their React upgrade now, this makes sense. In today's working group, there were no objections but we will revisit this with a larger audience next week.

**Comment by pcln-james** [comment]
Discussed in today's meeting and the conclusion was that this does need to be a major bump, however if we can make it a very simple major with the latest version of React being the only breaking change, then moving from v3 to v4 will be trivial for all teams. Internally, this should already be possible.

**Comment by craigpalermo** [comment]
Closing because this is already done on `next-v4`
