### ISSUE TITLE
Reduce / Remove Delayed Modal Open

### ISSUE THREAD

**Issue by pcln-james** [priceline/design-system#757]
The Priceline Modal opens slowly, I suspect it's due to the timeout prop that exists on the transition component. We should test that this hypothesis is correct and if so create a timeout prop with a default of 500 (the current value) that can be changed to reduce this delay.

**Comment by craigpalermo** [comment]
@wesleymartin85 Should we allow this animation duration to be fully configurable, or would it make sense to make it binary (e.g. animate vs don't animate)?

**Comment by wesleymartin85** [comment]
fully configurable I think would be best, but would it be crazy to ask for both configurable and binary?

**Comment by craigpalermo** [comment]
I think what @pcln-james has makes sense then; it defaults to the old `500ms` duration, and you can turn that off by making that prop `0`. That should be simple enough for now that we don't need to add more ways to control it.
