### ISSUE TITLE
Add a .github folder

### ISSUE THREAD

**Issue by rajat2502** [priceline/design-system#776]
We should add a `.github` folder in the root of the repository.
The folder should contain:

- [ ] Issue Templates
- [ ] Pull Request Templates

**Comment by craigpalermo** [comment]
Good idea, @rajat2502. Would you like to put something together for these?

@sdalonzo maybe we could also add `CODEOWNERS` to the list. 🤔

**Comment by rajat2502** [comment]
> Good idea, @rajat2502. Would you like to put something together for these?

Yeah, sure.
Do we need a different issue template for bugs and features or should I make a general issue template?

**Comment by sdalonzo** [comment]
I think we could start with a general one and see how it goes, and possibly split it later if it proves necessary. Thanks @rajat2502

**Comment by rajat2502** [comment]
Sure, I will make a general template then.
