### ISSUE TITLE
RatingBadge color prop doesn't work without bg

### ISSUE THREAD

**Issue by craigpalermo** [priceline/design-system#840]
**Describe the bug**
The `color` prop on `RatingBadge` doesn't work correctly unless the `bg` prop is an empty string.

**Affected project(s) (e.g. `pcln-design-system`, `pcln-modal`, etc.)**
pcln-design-system

**To Reproduce**
Use `RatingBadge` with a `color` prop, but no `bg`

**Expected behavior**
Color prop should work without providing any `bg` prop

**Screenshots**
<img width="795" alt="Screen Shot 2020-06-02 at 12 43 57 PM" src="https://user-images.githubusercontent.com/3260642/83548074-2e4ade00-a4d1-11ea-8d9b-f1602b67df44.png">
<img width="796" alt="Screen Shot 2020-06-02 at 12 43 48 PM" src="https://user-images.githubusercontent.com/3260642/83548076-2ee37480-a4d1-11ea-988c-261fd19a6846.png">

**Additional context**

**Comment by sdalonzo** [comment]
Good catch! We should be sure to write a proper unit test for this, not a snapshot.

**Comment by craigpalermo** [comment]
WIP
