### ISSUE TITLE
Deprecated prop warnings when running tests

### ISSUE THREAD

**Issue by craigpalermo** [priceline/design-system#845]
**Describe the bug**
All tests pass, but console shows warnings about deprecated props. We should update tests to use the latest/recommended props.

**Affected project(s) (e.g. `pcln-design-system`, `pcln-modal`, etc.)**
All

**To Reproduce**

1. Run the tests via `npm test`

**Expected behavior**
Tests shouldn't emit warnings

**Screenshots**
<img width="1066" alt="Screen Shot 2020-06-05 at 10 52 40 AM" src="https://user-images.githubusercontent.com/3260642/83891572-62b1da80-a71b-11ea-9425-e45cd9b530c2.png">

**Comment by sdalonzo** [comment]
Yes, please! This is a pet peeve

**Comment by craigpalermo** [comment]
We should ensure that this issue doesn't remove warnings from tests that are intended to test the functionality of deprecated warnings.
