### ISSUE TITLE
Codemod to replace old imports from pcln-icons/lib

### ISSUE THREAD

**Issue by craigpalermo** [priceline/design-system#859]
**Is your feature request related to a problem? Please describe.**
Should be able to transform multiple individual icon imports from `pcln-icons/lib/` into a single named import from `pcln-icons`.

Special cases to handle (or document):
- import as syntax
- preserving `'` vs `"`, but linters should handle this anyway
- imports named differently than the default export of the imported package

**Describe the solution you'd like**
Use jscodeshift.

**Additional context**
I'll create a section for this on the v3 migration guide once it's complete.

**Comment by craigpalermo** [comment]
I have a transform written for this that seems to work pretty well. I'll probably put up a PR tomorrow.

**Comment by sdalonzo** [comment]
your third special case describes enough implementations for me to question whether this is useful. we should discuss.

**Comment by craigpalermo** [comment]
Here's an example of how it handles the third case. The only additional step is preserving the named import so the original code still works.

<img width="1562" alt="Screen Shot 2020-06-26 at 10 17 22 PM" src="https://user-images.githubusercontent.com/3260642/85912482-d87d0380-b7fa-11ea-90c6-3fb19d35d47b.png">

**Comment by sdalonzo** [comment]
very nice!
