### ISSUE TITLE
Increase React and React DOM peer floor to 16.10

### ISSUE THREAD

**Issue by craigpalermo** [priceline/design-system#861]
In order to support React hooks, we need to raise the minimum supported versions of `react` and `react-dom`.

**Comment by craigpalermo** [comment]
@sdalonzo Should this apply to just `pcln-design-system`, or the non-core packages as well?

**Comment by sdalonzo** [comment]
I'm going to do it across the board. We want to keep majors in sync anyway (everything should be 4.x after)
