### ISSUE TITLE
Pre-commit check for internal registry URLs should log offending files

### ISSUE THREAD

**Issue by craigpalermo** [priceline/design-system#874]
**Is your feature request related to a problem? Please describe.**
To make debugging easier, [no-internal-registry](https://github.com/priceline/design-system/blob/master/githooks/no-internal-registry.js) should log which `package-lock.json` files contain internal URLs so the developer can see which files they need to delete/update.

**Describe the solution you'd like**
Should log which files it found that contain internal URLs.

**Comment by bmansell** [comment]
I think this one can be closed, I can see this is running on pre-commit and was able to find and correct my `core/package-lock.json` and `types/package-lock.json` files the other day thanks to this tool!

https://github.com/priceline/design-system/blob/b75b24e7bdd61bc2888a1f6f7327d119ea9371da/package.json#L80

https://github.com/priceline/design-system/blob/b75b24e7bdd61bc2888a1f6f7327d119ea9371da/githooks/no-internal-registry.js#L32

**Comment by sdalonzo** [comment]
as @pcln-brianna noted, @craigpalermo fixed this.
