### ISSUE TITLE
JS is not loaded for the design-system doc

### ISSUE THREAD

**Issue by hakimelek** [priceline/design-system#885]
**Describe the bug**
I noticed that none of the JS is working in the docs site. It seems like the paths broke during build time:
![image](https://user-images.githubusercontent.com/1974993/88311167-8e464f80-ccde-11ea-96b1-5e7fe09d63cc.png)

**Affected project(s) (e.g. `pcln-design-system`, `pcln-modal`, etc.)**
docs

**Comment by craigpalermo** [comment]
@hakimelek Thanks for the heads up, I'll look into this. It might be related to the switch to GitHub Actions.
