### ISSUE TITLE
Hotels FE is having an issue with <Text> not accepting a width prop for IE

### ISSUE THREAD

**Issue by tfquirk** [priceline/design-system#896]
**Describe the bug**
For IE we want to give the `<Text>` component a defined width because without it IE is not displaying it properly. 

![Screen Shot 2020-07-30 at 12 26 03 PM](https://user-images.githubusercontent.com/44677020/88948677-3371a280-d260-11ea-8821-2a54277878e9.png)

**Potential Solutions**
We could simply add a width prop to the Text component, or we could have the Text component be built on top of the Box component. Right now, Text is just a styled.div.

**Comment by craigpalermo** [comment]
Hey @tfquirk, thanks for reporting this. With your recent additions to `Box`, would it be possible to do something like this?

```javascript
<Box maxWidth="200px">
  <Text>I'm really long text that should have max width</Text>
</Box>
```

We'd probably have to be more careful if we wanted to make `Text` a styled `Box` instead of just a `div`.

**Comment by tfquirk** [comment]
@craigpalermo, for sure it will be in the future. (I don't think my recent updates have been released yet).

This was our current fix which works:
`
<Box width={1}>
  <Text>I'm really long text that has a width because of my parent Box.</Text>
</Box>
`

Ideally, however, we would not need to wrap additional divs around `<Text>` boxes to support css for width.

**Comment by craigpalermo** [comment]
@tfquirk Totally agreed about not wanting to have to wrap in `Box` just for CSS; my one concern about extending `Box` is that the color props would collide. I think the solution might be to replicate your recent changes to `Box` on `Text`.

**Comment by tfquirk** [comment]
We certainly don't have to build it on top of box, the other solution I had suggested was just to give text a width prop as well (or any other props the DS team wanted to add to it). 

I am happy to go whichever route, works best of the team. Or we could decide not to change text all, and work within the current constraints.

**Comment by craigpalermo** [comment]
@tfquirk Unless anyone is opposed, I think supporting `width` and related props on `Text` sounds like a great idea 😄

**Comment by tfquirk** [comment]
> @tfquirk Unless anyone is opposed, I think supporting `width` and related props on `Text` sounds like a great idea 😄

Awesome, I'll give this time for anyone else to review this convo and weigh in as well. And then I will be happy to own the work to get it done.

**Comment by craigpalermo** [comment]
Sounds good, I'll assign you to this issue then. Thanks!

**Comment by sdalonzo** [comment]
yea, the only question to me is what additional props (if any) do we want? since those would be purely additive anyway, there's no reason not to add width now (and overflow if it's not already there)

**Comment by tfquirk** [comment]
I would say all of these could be up for discussion:
```
 display
 height
 maxHeight
 maxWidth
 minHeight
 minWidth
width
```
