### ISSUE TITLE
pcln-popover content drops theme (at least the font family)

### ISSUE THREAD

**Issue by pcln-james** [priceline/design-system#976]
**Describe the bug**
Popover content doesn't inherit the theme properly, this is visible due to the font family not appearing on Text components inside of the popover content unless you specifically set it using styled-components.

**Affected project(s) (e.g. `pcln-design-system`, `pcln-modal`, etc.)**
pcln-popover

**To Reproduce**
Create a popover component with some text in the content.

**Expected behavior**
Text should be using Montserrat font family

**Screenshots**

Current Behaviour:
![image](https://user-images.githubusercontent.com/62619213/101105089-4f7cac00-3592-11eb-9382-8799c8beb454.png)

Expected Behaviour:
![image](https://user-images.githubusercontent.com/62619213/101105114-5dcac800-3592-11eb-9879-18cbd25ad139.png)

**Desktop (please complete the following information):**

- OS: MacOS 10.15.7
- Browser: Chrome
- Version: pcln-popover@4.0.0

I believe this issue is a result of ThemeProvider not wrapping the ReactPortal that is created by the Popover but not exactly sure of the best solution.

**Comment by craigpalermo** [comment]
WIP
